//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, UIImageView, UILabel;

@interface ALTabBar : UIView
{
    UIImageView *_backgroundImageView;
    NSArray *_items;
    id <ALTabBarDelegate> _delegate;
    int _buttonsSpacing;
    int _layoutMode;
    int _buttonsPadding;
    UIView *_badgeView;
    UILabel *_badgeLabel;
}

@property(retain, nonatomic) UILabel *badgeLabel; // @synthesize badgeLabel=_badgeLabel;
@property(retain, nonatomic) UIView *badgeView; // @synthesize badgeView=_badgeView;
@property(nonatomic) int layoutMode; // @synthesize layoutMode=_layoutMode;
@property(nonatomic) int buttonsPadding; // @synthesize buttonsPadding=_buttonsPadding;
@property(nonatomic) int buttonsSpacing; // @synthesize buttonsSpacing=_buttonsSpacing;
@property(retain, nonatomic) id <ALTabBarDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
- (void)setBackgroundContentMode:(int)arg1;
- (void)setBackgroundImage:(id)arg1;
- (void)tapItem:(int)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)buildBackgroundLayout;
- (void)buildButtonsLayout;
- (void)tabBarButtonPressed:(id)arg1;

@end

