//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSMutableArray, NSMutableData;

@interface AnimatedGif : NSObject
{
    NSData *GIF_pointer;
    NSMutableData *GIF_buffer;
    NSMutableData *GIF_screen;
    NSMutableData *GIF_global;
    NSMutableData *GIF_frameHeader;
    NSMutableArray *GIF_delays;
    NSMutableArray *GIF_framesData;
    int GIF_sorted;
    int GIF_colorS;
    int GIF_colorC;
    int GIF_colorF;
    int animatedGifDelay;
    int dataPointer;
}

+ (void)getAnimationForGifAtUrl:(id)arg1 withDelegate:(id)arg2 withImageView:(id)arg3;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (_Bool)GIFSkipBytes:(int)arg1;
- (_Bool)GIFGetBytes:(int)arg1;
- (void)GIFReadDescriptor;
- (void)GIFReadExtensions;
- (id)getAnimation:(id)arg1 imageView:(id)arg2;
- (id)getFrameAsImageAtIndex:(int)arg1;
- (id)getFrameAsDataAtIndex:(int)arg1;
- (void)decodeGIF:(id)arg1;
- (id)init;
- (void)loadWithData:(id)arg1 imageView:(id)arg2 filePath:(id)arg3 delegate:(id)arg4;

@end

