//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFHTTPSessionManager.h"

@interface APIClient : AFHTTPSessionManager
{
}

+ (id)sharedClient;
- (id)registerWithUsername:(id)arg1 email:(id)arg2 password:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (id)getNotificationsWithType:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)markNotificationsAsReadWithNotificationType:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)getUnreadNotificationsWithToken:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (id)getConversationsWithToken:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (id)deleteConversationWithUserId:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)postFollowRequestWithRequestId:(id)arg1 status:(int)arg2 token:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (id)postMessagesWithUserId:(id)arg1 token:(id)arg2 message:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (id)getMessagesWithUserId:(id)arg1 token:(id)arg2 limit:(int)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (id)getGifDetailsWithGifId:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)loginWithUsername:(id)arg1 password:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)loginWithOauthProvider:(id)arg1 oAuthId:(id)arg2 oAuthToken:(id)arg3 oAuthSecret:(id)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (id)postSettingsWithFields:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)uploadAvatarWithImageData:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)postUsername:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)getSettingsWithToken:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (id)getProfileWithUserId:(id)arg1 username:(id)arg2 limit:(int)arg3 start:(int)arg4 token:(id)arg5 success:(CDUnknownBlockType)arg6 failure:(CDUnknownBlockType)arg7;
- (id)sendCommandToGif:(id)arg1 token:(id)arg2 command:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (id)reportGifWithId:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)unlikeGifWithId:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)likeGifWithId:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)sendCommandToUser:(id)arg1 token:(id)arg2 command:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (id)unblockUserWithId:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)blockUserWithId:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)unfollowUserWithId:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)followUserWithId:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)getStreamWithLimit:(int)arg1 start:(int)arg2 token:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (id)searchForUserWithName:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)editGif:(id)arg1 blurb:(id)arg2 token:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (id)deleteGif:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)uploadGifCommentWithImageData:(id)arg1 token:(id)arg2 progress:(CDUnknownBlockType)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)uploadGifWithBlurb:(id)arg1 hidden:(BOOL)arg2 imageData:(id)arg3 token:(id)arg4 progress:(CDUnknownBlockType)arg5 success:(CDUnknownBlockType)arg6 failure:(CDUnknownBlockType)arg7;
- (id)postMessage:(id)arg1 userId:(id)arg2 image:(id)arg3 folder:(id)arg4 token:(id)arg5 success:(CDUnknownBlockType)arg6 failure:(CDUnknownBlockType)arg7;
- (id)deleteComment:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)postComment:(id)arg1 imageId:(id)arg2 image:(id)arg3 folder:(id)arg4 token:(id)arg5 success:(CDUnknownBlockType)arg6 failure:(CDUnknownBlockType)arg7;
- (id)getCommentsWithImageId:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)updateDeviceTokenWithDeviceToken:(id)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)getFeedWithAmount:(int)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)getTrendingWithAmount:(int)arg1 token:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;

@end

