//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "ALTabBarControllerDelegate.h"
#import "UIApplicationDelegate.h"

@class ALTabBarController, HomeViewController, NSString, NotificationsViewController, PopularViewController, SettingsMenuViewController, UIWindow;

@interface AppDelegate : UIResponder <UIApplicationDelegate, ALTabBarControllerDelegate>
{
    UIWindow *_window;
    ALTabBarController *_tabBarController;
    int previousTab;
    SettingsMenuViewController *svc;
    PopularViewController *pvc;
    HomeViewController *hvc;
    NotificationsViewController *nvc;
}

@property(retain, nonatomic) NotificationsViewController *nvc; // @synthesize nvc;
@property(retain, nonatomic) HomeViewController *hvc; // @synthesize hvc;
@property(retain, nonatomic) PopularViewController *pvc; // @synthesize pvc;
@property(retain, nonatomic) SettingsMenuViewController *svc; // @synthesize svc;
@property(nonatomic) int previousTab; // @synthesize previousTab;
@property(retain, nonatomic) ALTabBarController *tabBarController; // @synthesize tabBarController=_tabBarController;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)tabBarController:(id)arg1 didSelectButtonAtIndex:(int)arg2;
- (void)dismissPreview;
- (void)resetLogin;
- (void)fetchNotifications;
- (BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)showMessage:(id)arg1 withTitle:(id)arg2;
- (void)userLoggedOut;
- (void)userLoggedIn;
- (void)applicationDidBecomeActive:(id)arg1;
- (BOOL)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)sessionStateChanged:(id)arg1 state:(unsigned int)arg2 error:(id)arg3;
- (void)notificationReceived:(id)arg1;
- (void)popAllTabs;
- (void)popAllTabsButCurrent;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

