//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TTTAttributedLabelDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class GIFCommentPopupViewController, GIFObject, NSArray, NSMutableArray, NSString, UITableView, UITableViewCell, UIView;

@interface CommentsViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, TTTAttributedLabelDelegate>
{
    BOOL commentsFetched;
    BOOL animatingSideSwipe;
    BOOL showKeyboard;
    UITableView *tableView;
    GIFObject *gifObject;
    NSMutableArray *dataItems;
    GIFCommentPopupViewController *popupViewController;
    UITableViewCell *sideSwipeCell;
    UIView *sideSwipeView;
    unsigned int sideSwipeDirection;
    NSMutableArray *buttons;
    NSArray *buttonData;
    NSString *replyName;
    NSString *authorID;
}

@property(retain, nonatomic) NSString *authorID; // @synthesize authorID;
@property(nonatomic) BOOL showKeyboard; // @synthesize showKeyboard;
@property(retain, nonatomic) NSString *replyName; // @synthesize replyName;
@property(retain, nonatomic) NSArray *buttonData; // @synthesize buttonData;
@property(retain, nonatomic) NSMutableArray *buttons; // @synthesize buttons;
@property(nonatomic) BOOL animatingSideSwipe; // @synthesize animatingSideSwipe;
@property(nonatomic) unsigned int sideSwipeDirection; // @synthesize sideSwipeDirection;
@property(retain, nonatomic) UIView *sideSwipeView; // @synthesize sideSwipeView;
@property(retain, nonatomic) UITableViewCell *sideSwipeCell; // @synthesize sideSwipeCell;
@property(retain, nonatomic) GIFCommentPopupViewController *popupViewController; // @synthesize popupViewController;
@property(nonatomic) BOOL commentsFetched; // @synthesize commentsFetched;
@property(retain, nonatomic) NSMutableArray *dataItems; // @synthesize dataItems;
@property(retain, nonatomic) GIFObject *gifObject; // @synthesize gifObject;
@property(nonatomic) UITableView *tableView; // @synthesize tableView;
- (void).cxx_destruct;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)keyboardWillBeHidden:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (void)attributedLabel:(id)arg1 didSelectLinkWithTextCheckingResult:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (BOOL)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)postComment:(id)arg1;
- (void)fetchComments;
- (void)touchUpInsideAction:(id)arg1;
- (void)setupSideSwipeView:(struct CGRect)arg1 withItem:(id)arg2;
- (void)animationDidStopThree:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)animationDidStopTwo:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)animationDidStopOne:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)removeSideSwipeView:(BOOL)arg1;
- (void)animationDidStopAddingSwipeView:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)addSwipeViewTo:(id)arg1 direction:(unsigned int)arg2;
- (void)swipe:(id)arg1 direction:(unsigned int)arg2;
- (void)swipeRight:(id)arg1;
- (void)swipeLeft:(id)arg1;
- (void)setupGestureRecognizers;
- (void)gifCommentPressed:(id)arg1;
- (void)gifPopupBackPressed;
- (void)gifItemPressed:(id)arg1;
- (void)backPressed:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

