//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FlurryPLCrashReporter, NSDate, NSMutableArray, NSMutableDictionary, NSString;

@interface FlurryGlobalVariableStorage : NSObject
{
    BOOL _udidEnabled;
    BOOL _sessionReportsOnCloseEnabled;
    BOOL _sessionReportsOnPauseEnabled;
    BOOL _backgroundSessionEnabled;
    BOOL _crashReportingEnabled;
    BOOL _eventLoggingEnabled;
    BOOL _startSessionCalled;
    BOOL _macAddressEnabled;
    BOOL _optOutSessionPending;
    NSString *_savedResponseUrl;
    NSString *_apiKey;
    int _pauseSecondsBeforeStartingNewSession;
    NSDate *_pauseTime;
    NSDate *_lastPageViewDate;
    NSString *_appVersion;
    NSString *_userID;
    int _age;
    NSString *_gender;
    NSMutableDictionary *_launchOptions;
    id _location;
    FlurryPLCrashReporter *_flurryCrashReporter;
    NSMutableArray *_originSets;
    NSMutableDictionary *_persistentGlobalsMap;
    NSMutableDictionary *_persistentCookiesMap;
}

+ (void)cleanup;
+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *originSets; // @synthesize originSets=_originSets;
@property BOOL optOutSessionPending; // @synthesize optOutSessionPending=_optOutSessionPending;
@property(retain, nonatomic) FlurryPLCrashReporter *flurryCrashReporter; // @synthesize flurryCrashReporter=_flurryCrashReporter;
@property BOOL macAddressEnabled; // @synthesize macAddressEnabled=_macAddressEnabled;
@property(retain) id location; // @synthesize location=_location;
@property(readonly) NSMutableDictionary *launchOptions; // @synthesize launchOptions=_launchOptions;
@property BOOL startSessionCalled; // @synthesize startSessionCalled=_startSessionCalled;
@property(copy) NSString *gender; // @synthesize gender=_gender;
@property int age; // @synthesize age=_age;
@property(copy) NSString *userID; // @synthesize userID=_userID;
@property BOOL eventLoggingEnabled; // @synthesize eventLoggingEnabled=_eventLoggingEnabled;
@property(copy) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property BOOL crashReportingEnabled; // @synthesize crashReportingEnabled=_crashReportingEnabled;
@property BOOL backgroundSessionEnabled; // @synthesize backgroundSessionEnabled=_backgroundSessionEnabled;
@property BOOL sessionReportsOnPauseEnabled; // @synthesize sessionReportsOnPauseEnabled=_sessionReportsOnPauseEnabled;
@property BOOL sessionReportsOnCloseEnabled; // @synthesize sessionReportsOnCloseEnabled=_sessionReportsOnCloseEnabled;
@property(retain) NSDate *lastPageViewDate; // @synthesize lastPageViewDate=_lastPageViewDate;
@property(retain) NSDate *pauseTime; // @synthesize pauseTime=_pauseTime;
@property int pauseSecondsBeforeStartingNewSession; // @synthesize pauseSecondsBeforeStartingNewSession=_pauseSecondsBeforeStartingNewSession;
@property BOOL udidEnabled; // @synthesize udidEnabled=_udidEnabled;
@property(copy, nonatomic) NSString *apiKey; // @synthesize apiKey=_apiKey;
@property(copy) NSString *savedResponseUrl; // @synthesize savedResponseUrl=_savedResponseUrl;
@property(readonly) NSMutableDictionary *persistentCookiesMap; // @synthesize persistentCookiesMap=_persistentCookiesMap;
- (id)getPersistentFilePath:(id)arg1;
- (id)persistentCookiesFilePath;
@property(readonly) NSMutableDictionary *persistentGlobalsMap; // @synthesize persistentGlobalsMap=_persistentGlobalsMap;
- (id)persistentGlobalsFilePath;
- (void)recordOrigin:(id)arg1 originVersion:(id)arg2 withParameters:(id)arg3;
- (void)savePersistentGlobalsToDisk;
- (void)writeDictionary:(id)arg1 toFile:(id)arg2;
- (void)initPersistentMap;
- (void)dealloc;
- (id)init;

@end

