//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UINavigationControllerDelegate.h"
#import "UITabBarControllerDelegate.h"
#import "UITableViewDelegate.h"

@class NSString;

@interface FlurryPageViewDelegate : NSObject <UINavigationControllerDelegate, UITabBarControllerDelegate, UITableViewDelegate>
{
    id <NSObject> _delegate;
    id _target;
}

+ (void)destroyDelegateOnTarget:(id)arg1;
+ (void)createDelegateOnTarget:(id)arg1;
+ (id)createInvocationOnSelector:(SEL)arg1 target:(id)arg2;
@property(retain, nonatomic) id target; // @synthesize target=_target;
@property(nonatomic) id <NSObject> delegate; // @synthesize delegate=_delegate;
- (void)tabBarController:(id)arg1 didEndCustomizingViewControllers:(id)arg2 changed:(BOOL)arg3;
- (void)tabBarController:(id)arg1 willEndCustomizingViewControllers:(id)arg2 changed:(BOOL)arg3;
- (void)tabBarController:(id)arg1 willBeginCustomizingViewControllers:(id)arg2;
- (void)tabBarController:(id)arg1 didSelectViewController:(id)arg2;
- (BOOL)tabBarController:(id)arg1 shouldSelectViewController:(id)arg2;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(BOOL)arg3;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(BOOL)arg3;
- (void)dealloc;
- (id)initWithTarget:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

