//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "RCSwitchDelegate.h"
#import "UITextFieldDelegate.h"

@class GPUImageBrightnessFilter, GPUImageContrastFilter, GPUImageGammaFilter, GPUImageOutput<GPUImageInput>, GPUImagePicture, GPUImageSaturationFilter, GPUImageView, GifExporter, NSArray, NSString, NSTimer, RCSwitchClone, UIImageView, UILabel, UIScrollView, UISlider, UIView;

@interface GifEditorViewController : UIViewController <UITextFieldDelegate, MFMailComposeViewControllerDelegate, RCSwitchDelegate>
{
    float speed;
    float contrast;
    float saturation;
    float brightness;
    float gamma;
    int state;
    GPUImageOutput<GPUImageInput> *filter;
    GPUImageSaturationFilter *saturationFilter;
    GPUImageBrightnessFilter *brightessFilter;
    GPUImageContrastFilter *contrastFilter;
    GPUImageGammaFilter *gammaFilter;
    GPUImagePicture *staticPicture;
    BOOL reversed;
    int lastImage;
    NSTimer *timer;
    GifExporter *gifExporter;
    RCSwitchClone *revSwitch;
    NSArray *speedValues;
    int fps;
    NSArray *images;
    UILabel *labelSpeed;
    UIView *sliderView;
    UISlider *slider;
    UIScrollView *filtersView;
    GPUImageView *gpuimageView;
    UIScrollView *menuScrollView;
    UIImageView *onTabArrow;
    UISlider *sliderSpeed;
    UIView *_bottomControlsView;
    UIImageView *_imageViewMask;
}

@property(nonatomic) __weak UIImageView *imageViewMask; // @synthesize imageViewMask=_imageViewMask;
@property(nonatomic) __weak UIView *bottomControlsView; // @synthesize bottomControlsView=_bottomControlsView;
@property(nonatomic) __weak UISlider *sliderSpeed; // @synthesize sliderSpeed;
@property(retain, nonatomic) UIImageView *onTabArrow; // @synthesize onTabArrow;
@property(retain, nonatomic) UIScrollView *menuScrollView; // @synthesize menuScrollView;
@property(retain, nonatomic) GPUImageView *gpuimageView; // @synthesize gpuimageView;
@property(retain, nonatomic) UIScrollView *filtersView; // @synthesize filtersView;
@property(nonatomic) __weak UISlider *slider; // @synthesize slider;
@property(retain, nonatomic) UIView *sliderView; // @synthesize sliderView;
@property(nonatomic) __weak UILabel *labelSpeed; // @synthesize labelSpeed;
@property(retain, nonatomic) NSArray *images; // @synthesize images;
@property(nonatomic) int fps; // @synthesize fps;
@property(retain, nonatomic) NSArray *speedValues; // @synthesize speedValues;
@property(nonatomic) __weak RCSwitchClone *revSwitch; // @synthesize revSwitch;
@property(retain, nonatomic) GifExporter *gifExporter; // @synthesize gifExporter;
@property(nonatomic) BOOL reversed; // @synthesize reversed;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer;
@property(nonatomic) int lastImage; // @synthesize lastImage;
- (void).cxx_destruct;
- (void)showPublishGIF:(id)arg1;
- (void)updateUserInterface:(id)arg1;
- (void)exportStarter;
- (void)startExport;
- (void)prepareStaticFilter;
- (void)setStaticFilter:(int)arg1;
- (void)filterClicked:(id)arg1;
- (void)removeAllTargets;
- (void)changeDisplayedPicture:(id)arg1;
- (void)onTick:(id)arg1;
- (void)setFilter:(id)arg1;
- (void)modifierFinished:(id)arg1;
- (void)changeModifiers:(id)arg1;
- (void)setAnimationSpeed;
- (void)valueChanged:(id)arg1 toValue:(BOOL)arg2;
- (void)setSpeed:(id)arg1;
- (void)goNext;
- (void)goBack;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

