//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel, UIProgressView, UIViewController<MFMailComposeViewControllerDelegate>;

@interface GifExporter : UIView
{
    BOOL shouldReturn;
    UIProgressView *progressView;
    UIViewController<MFMailComposeViewControllerDelegate> *viewController;
    UILabel *label2;
}

@property(retain, nonatomic) UILabel *label2; // @synthesize label2;
@property(retain, nonatomic) UIViewController<MFMailComposeViewControllerDelegate> *viewController; // @synthesize viewController;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView;
- (void).cxx_destruct;
- (void)finish;
- (void)setProgressWithCurrent:(int)arg1 total:(int)arg2;
- (id)initWithViewController:(id)arg1;

@end

