//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSMutableArray, NSString;

@interface GIFObject : NSObject
{
    NSString *thumbnail;
    NSString *imageURL;
    NSString *blob;
    int comments;
    int views;
    int likes;
    NSDate *postedDate;
    NSString *username;
    NSString *avatarURL;
    NSString *userID;
    NSString *imageID;
    NSMutableArray *latestComments;
    int _width;
    int _height;
}

@property(nonatomic) int height; // @synthesize height=_height;
@property(nonatomic) int width; // @synthesize width=_width;
@property(retain, nonatomic) NSMutableArray *latestComments; // @synthesize latestComments;
@property(retain, nonatomic) NSString *imageID; // @synthesize imageID;
@property(retain, nonatomic) NSString *userID; // @synthesize userID;
@property(retain, nonatomic) NSString *avatarURL; // @synthesize avatarURL;
@property(retain, nonatomic) NSString *username; // @synthesize username;
@property(retain, nonatomic) NSDate *postedDate; // @synthesize postedDate;
@property(nonatomic) int likes; // @synthesize likes;
@property(nonatomic) int views; // @synthesize views;
@property(nonatomic) int comments; // @synthesize comments;
@property(retain, nonatomic) NSString *blob; // @synthesize blob;
@property(retain, nonatomic) NSString *imageURL; // @synthesize imageURL;
@property(retain, nonatomic) NSString *thumbnail; // @synthesize thumbnail;
- (void).cxx_destruct;
- (id)init;

@end

