//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "AnimatedGifDelegate.h"
#import "TTTAttributedLabelDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UIScrollViewDelegate.h"

@class GIFObject, NSString, UIButton, UIImageView, UILabel, UIProgressView, UIScrollView, UIView;

@interface GIFViewController : UIViewController <AnimatedGifDelegate, TTTAttributedLabelDelegate, UIAlertViewDelegate, UIScrollViewDelegate>
{
    BOOL liked;
    BOOL reported;
    UIImageView *avatarImageView;
    UILabel *usernameLabel;
    UILabel *likesLabel;
    UILabel *commentsLabel;
    UILabel *viewsLabel;
    UILabel *timeLabel;
    UIScrollView *innerScrollView;
    GIFObject *gifObject;
    UIButton *editButton;
    UIButton *likeButton;
    UIButton *reportButton;
    UIButton *commentButton;
    UIImageView *phoneSourceImageView;
    UIProgressView *progressView;
    UIImageView *imageView;
    UIView *phoneSourceView;
    int prevOffset;
    UIView *_scrollableView;
    UIImageView *_topBarImageView;
}

@property(nonatomic) __weak UIImageView *topBarImageView; // @synthesize topBarImageView=_topBarImageView;
@property(nonatomic) __weak UIView *scrollableView; // @synthesize scrollableView=_scrollableView;
@property(nonatomic) int prevOffset; // @synthesize prevOffset;
@property(nonatomic) __weak UIView *phoneSourceView; // @synthesize phoneSourceView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView;
@property(nonatomic) __weak UIImageView *phoneSourceImageView; // @synthesize phoneSourceImageView;
@property(nonatomic) BOOL reported; // @synthesize reported;
@property(nonatomic) BOOL liked; // @synthesize liked;
@property(nonatomic) __weak UIButton *commentButton; // @synthesize commentButton;
@property(nonatomic) __weak UIButton *reportButton; // @synthesize reportButton;
@property(nonatomic) __weak UIButton *likeButton; // @synthesize likeButton;
@property(nonatomic) __weak UIButton *editButton; // @synthesize editButton;
@property(retain, nonatomic) GIFObject *gifObject; // @synthesize gifObject;
@property(nonatomic) __weak UIScrollView *innerScrollView; // @synthesize innerScrollView;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel;
@property(nonatomic) __weak UILabel *viewsLabel; // @synthesize viewsLabel;
@property(nonatomic) __weak UILabel *commentsLabel; // @synthesize commentsLabel;
@property(nonatomic) __weak UILabel *likesLabel; // @synthesize likesLabel;
@property(nonatomic) __weak UILabel *usernameLabel; // @synthesize usernameLabel;
@property(nonatomic) __weak UIImageView *avatarImageView; // @synthesize avatarImageView;
- (void).cxx_destruct;
- (void)dealloc;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)scrollViewDidScroll:(id)arg1;
- (void)viewDidLoad;
- (void)hideUserDetailsBar;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)dismissProgressIndicator;
- (void)progressUpdate:(float)arg1;
- (void)animatedGifRequestFinished;
- (void)requestFailed:(id)arg1;
- (void)requestFinished:(id)arg1;
- (void)fetchDataWithDetails:(BOOL)arg1;
- (void)fetchPictureDetails:(id)arg1 token:(id)arg2;
- (void)report:(id)arg1 token:(id)arg2;
- (void)unlike:(id)arg1 token:(id)arg2;
- (void)like:(id)arg1 token:(id)arg2;
- (void)attributedLabel:(id)arg1 didSelectLinkWithTextCheckingResult:(id)arg2;
- (void)setupDate;
- (void)setupViews;
- (void)setupButtons;
- (void)sharePressed:(id)arg1;
- (void)editPressed:(id)arg1;
- (void)backPressed:(id)arg1;
- (void)likePressed:(id)arg1;
- (void)commentPressed:(id)arg1;
- (void)reportPressed:(id)arg1;
- (void)userPressed:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

