//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIScrollViewDelegate.h"

@class NSMutableArray, NSString, UIScrollView;

@interface GridViewController : UIViewController <UIScrollViewDelegate>
{
    BOOL showMore;
    BOOL fetchingPage;
    NSMutableArray *GOArray;
    UIScrollView *thumbnailsScrollView;
    NSMutableArray *thumbnailsArray;
    UIViewController *masterViewController;
    id <GridViewDelegate> delegate;
    int currentPage;
}

@property(nonatomic) BOOL fetchingPage; // @synthesize fetchingPage;
@property(nonatomic) int currentPage; // @synthesize currentPage;
@property(nonatomic) id <GridViewDelegate> delegate; // @synthesize delegate;
@property(nonatomic) BOOL showMore; // @synthesize showMore;
@property(retain, nonatomic) UIViewController *masterViewController; // @synthesize masterViewController;
@property(retain, nonatomic) NSMutableArray *thumbnailsArray; // @synthesize thumbnailsArray;
@property(nonatomic) __weak UIScrollView *thumbnailsScrollView; // @synthesize thumbnailsScrollView;
@property(retain, nonatomic) NSMutableArray *GOArray; // @synthesize GOArray;
- (void).cxx_destruct;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)clearView;
- (void)getThumbnails;
- (void)thumbnailTapped:(id)arg1;
- (void)reloadImageScrollView;
- (void)removePhotoFromScrollView:(id)arg1;
- (void)addPhotoToScrollView:(id)arg1 toBack:(unsigned char)arg2;
- (void)scrollViewDidScroll:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

