//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ListViewDelegate.h"

@class ListViewController, MBProgressHUD, NSMutableArray, NSString, UIImageView, UIView;

@interface HomeViewController : UIViewController <ListViewDelegate>
{
    BOOL fetching;
    UIImageView *noActivityImageView;
    UIView *mainView;
    MBProgressHUD *hud;
    NSMutableArray *GOArray;
    ListViewController *lvc;
}

@property(nonatomic) BOOL fetching; // @synthesize fetching;
@property(retain, nonatomic) ListViewController *lvc; // @synthesize lvc;
@property(retain, nonatomic) NSMutableArray *GOArray; // @synthesize GOArray;
@property(retain, nonatomic) MBProgressHUD *hud; // @synthesize hud;
@property(retain, nonatomic) UIView *mainView; // @synthesize mainView;
@property(retain, nonatomic) UIImageView *noActivityImageView; // @synthesize noActivityImageView;
- (void).cxx_destruct;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewWillAppear:(BOOL)arg1;
- (void)restartView;
- (void)fetchListWithPage:(int)arg1;
- (void)listViewLoadPage:(int)arg1;
- (void)dismissHUD:(id)arg1;
- (void)requestFinished:(id)arg1;
- (void)refresh;
- (void)refreshPressed:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

