//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MFMessageComposeViewControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MBProgressHUD, NSMutableArray, NSString, UIButton, UITableView, UIView;

@interface InviteFriendsViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, MFMessageComposeViewControllerDelegate>
{
    UIView *_placeholderView;
    UITableView *_tableView;
    UIButton *_facebookButton;
    UIButton *_contactsButton;
    NSMutableArray *_friendsArray;
    int _currentTab;
    MBProgressHUD *_hud;
}

@property(retain, nonatomic) MBProgressHUD *hud; // @synthesize hud=_hud;
@property(nonatomic) int currentTab; // @synthesize currentTab=_currentTab;
@property(retain, nonatomic) NSMutableArray *friendsArray; // @synthesize friendsArray=_friendsArray;
@property(retain, nonatomic) UIButton *contactsButton; // @synthesize contactsButton=_contactsButton;
@property(retain, nonatomic) UIButton *facebookButton; // @synthesize facebookButton=_facebookButton;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIView *placeholderView; // @synthesize placeholderView=_placeholderView;
- (void).cxx_destruct;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)showThankYouAlertView;
- (void)dialogCompleteWithUrl:(id)arg1;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
- (void)buildContactListWithAddressBookRef:(void *)arg1;
- (void)fetchContacts;
- (void)addFriendToArray:(id)arg1 normalLabel:(id)arg2 avatarURL:(id)arg3 withID:(id)arg4;
- (void)sortFriendsArray;
- (void)contactsError;
- (void)donePressed:(id)arg1;
- (void)invitePressed:(id)arg1;
- (void)pullContacts;
- (void)dismissHUD:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

