//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString, UIColor;

@interface Item : NSObject
{
    BOOL resizeable;
    BOOL reversed;
    BOOL deletable;
    BOOL highlighted;
    BOOL arrowVisible;
    BOOL imageVisible;
    BOOL big;
    BOOL smallComment;
    BOOL wantsToFollow;
    BOOL _checkbox;
    NSString *name;
    NSString *text;
    NSString *date;
    NSDate *posted;
    NSString *poster_id;
    NSString *post_id;
    NSString *receiver_id;
    int tag;
    NSString *avatar;
    NSString *gif_url;
    NSString *thumb_url;
    NSString *notification_id;
    UIColor *color;
    int _source;
}

@property(nonatomic) BOOL checkbox; // @synthesize checkbox=_checkbox;
@property(nonatomic) int source; // @synthesize source=_source;
@property(retain, nonatomic) UIColor *color; // @synthesize color;
@property(retain, nonatomic) NSString *notification_id; // @synthesize notification_id;
@property(nonatomic) BOOL wantsToFollow; // @synthesize wantsToFollow;
@property(nonatomic) BOOL smallComment; // @synthesize smallComment;
@property(retain, nonatomic) NSString *thumb_url; // @synthesize thumb_url;
@property(retain, nonatomic) NSString *gif_url; // @synthesize gif_url;
@property(nonatomic) BOOL big; // @synthesize big;
@property(nonatomic) BOOL imageVisible; // @synthesize imageVisible;
@property(nonatomic) BOOL arrowVisible; // @synthesize arrowVisible;
@property(retain, nonatomic) NSString *avatar; // @synthesize avatar;
@property(nonatomic) BOOL highlighted; // @synthesize highlighted;
@property(nonatomic) int tag; // @synthesize tag;
@property(nonatomic) BOOL deletable; // @synthesize deletable;
@property(nonatomic) BOOL reversed; // @synthesize reversed;
@property(nonatomic) BOOL resizeable; // @synthesize resizeable;
@property(retain, nonatomic) NSString *receiver_id; // @synthesize receiver_id;
@property(retain, nonatomic) NSString *post_id; // @synthesize post_id;
@property(retain, nonatomic) NSString *poster_id; // @synthesize poster_id;
@property(retain, nonatomic) NSDate *posted; // @synthesize posted;
@property(retain, nonatomic) NSString *date; // @synthesize date;
@property(retain, nonatomic) NSString *text; // @synthesize text;
@property(retain, nonatomic) NSString *name; // @synthesize name;
- (void).cxx_destruct;
- (void)setPostedWithDate:(id)arg1 time:(id)arg2;

@end

