//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "TTTAttributedLabelDelegate.h"

@class MaskView, NSArray, NSMutableArray, NSMutableDictionary, NSString, UIActivityIndicatorView, UIViewController;

@interface ListViewController : UITableViewController <TTTAttributedLabelDelegate>
{
    BOOL showMore;
    NSArray *GOArray;
    NSMutableArray *sectionGOArray;
    UIViewController *masterViewController;
    NSMutableArray *imageCellIndexes;
    MaskView *maskView;
    NSMutableDictionary *maskFramesDictionary;
    id <ListViewDelegate> delegate;
    int currentPage;
    NSMutableDictionary *headerImagesDictionary;
    UIActivityIndicatorView *activityIndicator;
    NSMutableArray *prefetchURLList;
}

@property(retain, nonatomic) NSMutableArray *prefetchURLList; // @synthesize prefetchURLList;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator;
@property(retain, nonatomic) NSMutableDictionary *headerImagesDictionary; // @synthesize headerImagesDictionary;
@property(nonatomic) int currentPage; // @synthesize currentPage;
@property(nonatomic) id <ListViewDelegate> delegate; // @synthesize delegate;
@property(nonatomic) BOOL showMore; // @synthesize showMore;
@property(retain, nonatomic) NSMutableDictionary *maskFramesDictionary; // @synthesize maskFramesDictionary;
@property(retain, nonatomic) MaskView *maskView; // @synthesize maskView;
@property(retain, nonatomic) NSMutableArray *imageCellIndexes; // @synthesize imageCellIndexes;
@property(retain, nonatomic) UIViewController *masterViewController; // @synthesize masterViewController;
@property(retain, nonatomic) NSMutableArray *sectionGOArray; // @synthesize sectionGOArray;
@property(retain, nonatomic) NSArray *GOArray; // @synthesize GOArray;
- (void).cxx_destruct;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)attributedLabel:(id)arg1 didSelectLinkWithTextCheckingResult:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)dealloc;
- (void)initializeSections;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)viewTouched:(id)arg1 withEvent:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)reloadData;
- (void)viewDidLoad;
- (id)initWithStyle:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

