//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextFieldDelegate.h"

@class CustomTextField, MBProgressHUD, NSString, PreviewViewController, UIScrollView;

@interface LoginViewController : UIViewController <UITextFieldDelegate>
{
    CustomTextField *loginTextField;
    CustomTextField *passwdTextField;
    MBProgressHUD *hud;
    PreviewViewController *pvc;
    UIScrollView *scrollView;
}

@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView;
@property(retain, nonatomic) PreviewViewController *pvc; // @synthesize pvc;
@property(retain, nonatomic) MBProgressHUD *hud; // @synthesize hud;
@property(nonatomic) __weak CustomTextField *passwdTextField; // @synthesize passwdTextField;
@property(nonatomic) __weak CustomTextField *loginTextField; // @synthesize loginTextField;
- (void).cxx_destruct;
- (void)dealloc;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)changeScrollViewContentToBig:(BOOL)arg1;
- (void)resignResponders;
- (void)hideKeyboard;
- (void)keyboardWillBeHidden:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)scrollViewToTextInput:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)requestFailed:(id)arg1;
- (void)requestFinished:(id)arg1;
- (void)login;
- (void)registerEmailPressed:(id)arg1;
- (void)forgotPressed:(id)arg1;
- (void)backPressed:(id)arg1;
- (void)loginPressed:(id)arg1;
- (void)twitterPressed:(id)arg1;
- (void)didLoginToFBWithUser:(id)arg1;
- (void)facebookPressed:(id)arg1;
- (void)dismissHUD:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

