//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "DeleteDelegate.h"
#import "TTTAttributedLabelDelegate.h"
#import "UIAlertViewDelegate.h"

@class NSMutableArray, NSString, UIButton, UIImageView, UILabel, UITableView, UIView;

@interface NotificationsViewController : UIViewController <TTTAttributedLabelDelegate, DeleteDelegate, UIAlertViewDelegate>
{
    BOOL fetchingBadges;
    BOOL fetchingList;
    UIButton *lastButton;
    UITableView *tableView;
    NSMutableArray *dataItems;
    UIButton *buttonMessages;
    UIButton *buttonAll;
    UIView *viewHighlight;
    UIImageView *imageShadow;
    UIImageView *badgeMessages;
    UILabel *labelMessages;
    UIImageView *badgeAll;
    UILabel *labelAll;
    NSString *followRequestID;
    UILabel *_labelInfo;
    int _lastTag;
}

@property(nonatomic) int lastTag; // @synthesize lastTag=_lastTag;
@property(nonatomic) __weak UILabel *labelInfo; // @synthesize labelInfo=_labelInfo;
@property(retain, nonatomic) NSString *followRequestID; // @synthesize followRequestID;
@property(nonatomic) BOOL fetchingList; // @synthesize fetchingList;
@property(nonatomic) BOOL fetchingBadges; // @synthesize fetchingBadges;
@property(nonatomic) __weak UILabel *labelAll; // @synthesize labelAll;
@property(nonatomic) __weak UIImageView *badgeAll; // @synthesize badgeAll;
@property(nonatomic) __weak UILabel *labelMessages; // @synthesize labelMessages;
@property(nonatomic) __weak UIImageView *badgeMessages; // @synthesize badgeMessages;
@property(nonatomic) __weak UIImageView *imageShadow; // @synthesize imageShadow;
@property(nonatomic) __weak UIView *viewHighlight; // @synthesize viewHighlight;
@property(nonatomic) __weak UIButton *buttonAll; // @synthesize buttonAll;
@property(nonatomic) __weak UIButton *buttonMessages; // @synthesize buttonMessages;
@property(retain, nonatomic) NSMutableArray *dataItems; // @synthesize dataItems;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView;
@property(nonatomic) __weak UIButton *lastButton; // @synthesize lastButton;
- (void).cxx_destruct;
- (void)requestFailed:(id)arg1;
- (void)downloadListForTag:(int)arg1;
- (void)downloadBadges;
- (void)deleteWithUser:(id)arg1;
- (void)buttonFollowersClicked:(id)arg1;
- (void)buttonAllClicked:(id)arg1;
- (void)buttonMessagesClicked:(id)arg1;
- (void)setAmount:(int)arg1 forBadge:(id)arg2 andLabel:(id)arg3;
- (void)animateToButton:(id)arg1;
- (void)attributedLabel:(id)arg1 didSelectLinkWithTextCheckingResult:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)tabChanged;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)restartView;
- (void)notificationReceived;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

