//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (STTwitter)
- (int)st_numberOfCharactersInATweet;
- (int)st_numberOfCharactersInATweetWithShortURLLength:(unsigned int)arg1 shortURLLengthHTTPS:(unsigned int)arg2;
- (id)st_firstMatchWithRegex:(id)arg1 error:(id *)arg2;
@end

