//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"

@class AVCaptureSession, AVCaptureVideoDataOutput, AVCaptureVideoPreviewLayer, CommentsViewController, ConversationViewController, NSArray, NSMutableArray, NSString, UIButton, UILabel, UIView;

@interface PhotoViewController : UIViewController <AVCaptureVideoDataOutputSampleBufferDelegate>
{
    BOOL flashON;
    BOOL isFront;
    int videoTime;
    int autoTime;
    int state;
    int recordType;
    int framesCount;
    int fps;
    float effectiveScale;
    float beginScale;
    int actionTag;
    CommentsViewController *commentsViewController;
    ConversationViewController *conversationViewController;
    UILabel *burstLabel;
    UILabel *singleLabel;
    UIView *viewSetFPSTime;
    UIView *viewSetAutoTime;
    UIView *viewSetVideoTime;
    UILabel *labelCountdown;
    NSArray *fpsArray;
    UIButton *buttonFPS;
    UIButton *buttonAuto;
    UIButton *buttonFlash;
    UIButton *buttonCamera;
    UIButton *buttonLength;
    AVCaptureSession *session;
    AVCaptureVideoPreviewLayer *captureVideoPreviewLayer;
    NSMutableArray *images;
    AVCaptureVideoDataOutput *output;
    UIButton *buttonBurstRecord;
    UIButton *buttonManualRecord;
    UILabel *labelProgressAll;
    UILabel *labelProgressCurrent;
}

@property(nonatomic) __weak UILabel *labelProgressCurrent; // @synthesize labelProgressCurrent;
@property(nonatomic) __weak UILabel *labelProgressAll; // @synthesize labelProgressAll;
@property(nonatomic) __weak UIButton *buttonManualRecord; // @synthesize buttonManualRecord;
@property(nonatomic) __weak UIButton *buttonBurstRecord; // @synthesize buttonBurstRecord;
@property(retain, nonatomic) AVCaptureVideoDataOutput *output; // @synthesize output;
@property(retain, nonatomic) NSMutableArray *images; // @synthesize images;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *captureVideoPreviewLayer; // @synthesize captureVideoPreviewLayer;
@property(retain, nonatomic) AVCaptureSession *session; // @synthesize session;
@property(nonatomic) __weak UIButton *buttonLength; // @synthesize buttonLength;
@property(nonatomic) __weak UIButton *buttonCamera; // @synthesize buttonCamera;
@property(nonatomic) __weak UIButton *buttonFlash; // @synthesize buttonFlash;
@property(nonatomic) __weak UIButton *buttonAuto; // @synthesize buttonAuto;
@property(nonatomic) __weak UIButton *buttonFPS; // @synthesize buttonFPS;
@property(retain, nonatomic) NSArray *fpsArray; // @synthesize fpsArray;
@property(nonatomic) __weak UILabel *labelCountdown; // @synthesize labelCountdown;
@property(nonatomic) __weak UIView *viewSetVideoTime; // @synthesize viewSetVideoTime;
@property(nonatomic) __weak UIView *viewSetAutoTime; // @synthesize viewSetAutoTime;
@property(nonatomic) __weak UIView *viewSetFPSTime; // @synthesize viewSetFPSTime;
@property(nonatomic) __weak UILabel *singleLabel; // @synthesize singleLabel;
@property(nonatomic) __weak UILabel *burstLabel; // @synthesize burstLabel;
@property(nonatomic) __weak ConversationViewController *conversationViewController; // @synthesize conversationViewController;
@property(nonatomic) __weak CommentsViewController *commentsViewController; // @synthesize commentsViewController;
@property(nonatomic) int actionTag; // @synthesize actionTag;
- (void).cxx_destruct;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (id)imageFromSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)capturePictures;
- (void)refreshLabelProgress;
- (void)handlePinch:(id)arg1;
- (void)applyZoom;
- (void)setLabelCountdownValue:(id)arg1;
- (void)startShooting;
- (void)setBurstRecord;
- (void)setManualRecord;
- (void)setVideoTime:(id)arg1;
- (void)setAutoTime:(id)arg1;
- (void)setFPS:(id)arg1;
- (void)showFPSTime;
- (void)showVideoTime;
- (void)showAutoTime;
- (void)reset;
- (void)goNext;
- (void)flashOn;
- (void)forceFlashOff;
- (void)changeCamera;
- (id)getNextCamera;
- (void)close;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

