//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UITextViewDelegate.h"

@class CommentsViewController, NSString, UIImageView, UITextView;

@interface PostCommentCell : UITableViewCell <UITextViewDelegate>
{
    UITextView *commentTextView;
    UIImageView *avatarImageView;
    CommentsViewController *commentsViewController;
}

@property(nonatomic) __weak CommentsViewController *commentsViewController; // @synthesize commentsViewController;
@property(nonatomic) __weak UIImageView *avatarImageView; // @synthesize avatarImageView;
@property(nonatomic) __weak UITextView *commentTextView; // @synthesize commentTextView;
- (void).cxx_destruct;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)gifCommentPressed:(id)arg1;
- (void)postPressed:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

