//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "GridViewDelegate.h"
#import "ListViewDelegate.h"

@class GridViewController, ListViewController, MBProgressHUD, NSMutableArray, NSString, UIButton, UIImageView, UILabel, UIView;

@interface ProfileViewController : UIViewController <ListViewDelegate, GridViewDelegate>
{
    BOOL isFollowingRequest;
    BOOL isFollowing;
    BOOL isPrivate;
    BOOL isBlocked;
    BOOL isFollowed;
    BOOL allowsAllPM;
    BOOL hideTabBar;
    int currentView;
    UIImageView *avatarImageView;
    UILabel *usernameLabel;
    UILabel *locationLabel;
    UILabel *countLabel;
    UILabel *followersLabel;
    UILabel *followingLabel;
    UIView *bottomView;
    UIButton *listButton;
    UIButton *gridButton;
    UIButton *followingButton;
    UIButton *messageButton;
    NSMutableArray *GOArray;
    NSString *userID;
    MBProgressHUD *hud;
    ListViewController *lvc;
    GridViewController *gvc;
    NSString *username;
    UILabel *aboutLabel;
    UIButton *blockButton;
    NSString *about;
    UIButton *viewMoreButton;
    UILabel *_messageLabel;
}

@property(nonatomic) __weak UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(nonatomic) __weak UIButton *viewMoreButton; // @synthesize viewMoreButton;
@property(retain, nonatomic) NSString *about; // @synthesize about;
@property(nonatomic) __weak UIButton *blockButton; // @synthesize blockButton;
@property(nonatomic) __weak UILabel *aboutLabel; // @synthesize aboutLabel;
@property(nonatomic) BOOL hideTabBar; // @synthesize hideTabBar;
@property(nonatomic) BOOL allowsAllPM; // @synthesize allowsAllPM;
@property(nonatomic) BOOL isFollowed; // @synthesize isFollowed;
@property(nonatomic) BOOL isBlocked; // @synthesize isBlocked;
@property(nonatomic) BOOL isPrivate; // @synthesize isPrivate;
@property(retain, nonatomic) NSString *username; // @synthesize username;
@property(retain, nonatomic) GridViewController *gvc; // @synthesize gvc;
@property(retain, nonatomic) ListViewController *lvc; // @synthesize lvc;
@property(retain, nonatomic) MBProgressHUD *hud; // @synthesize hud;
@property(retain, nonatomic) NSString *userID; // @synthesize userID;
@property(retain, nonatomic) NSMutableArray *GOArray; // @synthesize GOArray;
@property(nonatomic) __weak UIButton *messageButton; // @synthesize messageButton;
@property(nonatomic) BOOL isFollowing; // @synthesize isFollowing;
@property(nonatomic) BOOL isFollowingRequest; // @synthesize isFollowingRequest;
@property(nonatomic) __weak UIButton *followingButton; // @synthesize followingButton;
@property(nonatomic) __weak UIButton *gridButton; // @synthesize gridButton;
@property(nonatomic) __weak UIButton *listButton; // @synthesize listButton;
@property(nonatomic) __weak UIView *bottomView; // @synthesize bottomView;
@property(nonatomic) __weak UILabel *followingLabel; // @synthesize followingLabel;
@property(nonatomic) __weak UILabel *followersLabel; // @synthesize followersLabel;
@property(nonatomic) __weak UILabel *countLabel; // @synthesize countLabel;
@property(nonatomic) __weak UILabel *locationLabel; // @synthesize locationLabel;
@property(nonatomic) __weak UILabel *usernameLabel; // @synthesize usernameLabel;
@property(nonatomic) __weak UIImageView *avatarImageView; // @synthesize avatarImageView;
@property(nonatomic) int currentView; // @synthesize currentView;
- (void).cxx_destruct;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)requestFinished:(id)arg1;
- (void)requestFailed:(id)arg1;
- (void)fetchUserDataWithUsername:(id)arg1 token:(id)arg2 page:(int)arg3;
- (void)fetchUserData:(id)arg1 token:(id)arg2 page:(int)arg3;
- (void)gridViewLoadPage:(int)arg1;
- (void)listViewLoadPage:(int)arg1;
- (void)loadPage:(int)arg1;
- (void)dismissHUD:(id)arg1;
- (void)setupButtons;
- (void)pushConversationView;
- (void)aboutPressed:(id)arg1;
- (void)blockPressed:(id)arg1;
- (void)messagePressed:(id)arg1;
- (void)followPressed:(id)arg1;
- (void)gridPressed:(id)arg1;
- (void)listPressed:(id)arg1;
- (void)backPressed:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

