//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "RCSwitchDelegate.h"
#import "UITextViewDelegate.h"

@class CustomTextView, MBProgressHUD, NSArray, NSString, RCSwitchClone, UIImageView, UILabel, UIScrollView, UIView;

@interface PublishGIFViewController : UIViewController <UITextViewDelegate, RCSwitchDelegate>
{
    BOOL canShareOnFB;
    BOOL canShareOnTwitter;
    UIScrollView *scrollView;
    CustomTextView *textView;
    UIView *streamSettingsView;
    UIView *textViewHolderView;
    UIImageView *imageView;
    UILabel *sizeLabel;
    NSString *filePath;
    RCSwitchClone *shareOnTwitterSwitch;
    RCSwitchClone *shareOnFacebookSwitch;
    RCSwitchClone *hideFromFeedSwitch;
    NSArray *labelArray;
    MBProgressHUD *hud;
    NSString *_userid;
    NSString *_username;
    NSString *_gifid;
    NSString *_thumbnailurl;
}

@property(retain, nonatomic) NSString *thumbnailurl; // @synthesize thumbnailurl=_thumbnailurl;
@property(retain, nonatomic) NSString *gifid; // @synthesize gifid=_gifid;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
@property(retain, nonatomic) NSString *userid; // @synthesize userid=_userid;
@property(nonatomic) BOOL canShareOnTwitter; // @synthesize canShareOnTwitter;
@property(nonatomic) BOOL canShareOnFB; // @synthesize canShareOnFB;
@property(retain, nonatomic) MBProgressHUD *hud; // @synthesize hud;
@property(retain, nonatomic) NSArray *labelArray; // @synthesize labelArray;
@property(nonatomic) __weak RCSwitchClone *hideFromFeedSwitch; // @synthesize hideFromFeedSwitch;
@property(nonatomic) __weak RCSwitchClone *shareOnFacebookSwitch; // @synthesize shareOnFacebookSwitch;
@property(nonatomic) __weak RCSwitchClone *shareOnTwitterSwitch; // @synthesize shareOnTwitterSwitch;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath;
@property(nonatomic) __weak UILabel *sizeLabel; // @synthesize sizeLabel;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView;
@property(nonatomic) __weak UIView *textViewHolderView; // @synthesize textViewHolderView;
@property(nonatomic) __weak UIView *streamSettingsView; // @synthesize streamSettingsView;
@property(nonatomic) __weak CustomTextView *textView; // @synthesize textView;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setProgress:(float)arg1;
- (void)requestFinished:(id)arg1;
- (void)shareOnFacebook:(id)arg1;
- (void)shareOnTwitter:(id)arg1;
- (void)share:(id)arg1;
- (void)dismissView;
- (void)backPressed:(id)arg1;
- (void)publishPressed:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)changeScrollViewContentToBig:(BOOL)arg1;
- (void)scrollViewToTextInput:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)keyboardWillBeHidden:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)hideKeyboard;
- (void)showSuccessHUDWithText:(id)arg1 timeout:(int)arg2;
- (void)dismissHUD:(id)arg1;
- (void)valueChanged:(id)arg1 toValue:(BOOL)arg2;
- (void)twitterRequestFailed:(id)arg1;
- (void)didLoginToFBWithUser:(id)arg1;
- (void)checkFBPublish;
- (void)FBError;
- (void)requestFBPublish;
- (void)showMessage:(id)arg1 withTitle:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

