//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSDate, UIImage;

@interface RCSwitch : UIControl
{
    UIImage *knobImage;
    UIImage *knobImageYes;
    UIImage *knobImageNo;
    UIImage *knobImagePressed;
    UIImage *sliderOff;
    UIImage *sliderOn;
    UIImage *buttonEndTrack;
    UIImage *buttonEndTrackPressed;
    float percent;
    float oldPercent;
    float knobWidth;
    float endcapWidth;
    struct CGPoint startPoint;
    float scale;
    float drawHeight;
    float animationDuration;
    struct CGSize lastBoundsSize;
    NSDate *endDate;
    BOOL mustFlip;
    BOOL revImages;
    id <RCSwitchDelegate> delegate;
}

@property(nonatomic) BOOL revImages; // @synthesize revImages;
@property(nonatomic) id <RCSwitchDelegate> delegate; // @synthesize delegate;
- (void)performSwitchToPercent:(float)arg1;
- (void)setOn:(BOOL)arg1 animated:(BOOL)arg2;
@property(getter=isOn) BOOL on;
- (void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)cancelTrackingWithEvent:(id)arg1;
- (void)finishEvent;
- (BOOL)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (BOOL)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawUnderlayersInRect:(struct CGRect)arg1 withOffset:(float)arg2 inTrackWidth:(float)arg3;
- (void)regenerateImages;
@property float knobWidth;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)initCommon;

@end

