//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCSwitch.h"

@class UIImage, UILabel;

@interface RCSwitchClone : RCSwitch
{
    UILabel *onText;
    UILabel *offText;
    UIImage *onImage;
    UIImage *offImage;
    BOOL useImage;
}

- (void)drawUnderlayersInRect:(struct CGRect)arg1 withOffset:(float)arg2 inTrackWidth:(float)arg3;
- (void)dealloc;
- (void)initCommon;

@end

