//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class CustomTextField, PreviewViewController;

@interface RegisterViewController : UIViewController
{
    PreviewViewController *_pvc;
    CustomTextField *_usernameField;
    CustomTextField *_emailField;
    CustomTextField *_passwordField;
}

@property(nonatomic) __weak CustomTextField *passwordField; // @synthesize passwordField=_passwordField;
@property(nonatomic) __weak CustomTextField *emailField; // @synthesize emailField=_emailField;
@property(nonatomic) __weak CustomTextField *usernameField; // @synthesize usernameField=_usernameField;
@property(nonatomic) __weak PreviewViewController *pvc; // @synthesize pvc=_pvc;
- (void).cxx_destruct;
- (BOOL)stringIsValidPassword:(id)arg1;
- (BOOL)stringIsValidName:(id)arg1;
- (BOOL)stringIsValidEmail:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)registerPressed:(id)arg1;
- (void)backPressed:(id)arg1;

@end

