//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSMutableArray, NSString, UILabel, UITableView;

@interface SelectImagesViewController : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    int numberOfSelectedImages;
    BOOL doubleTap;
    NSArray *imagesArray;
    UILabel *labelInfo;
    NSMutableArray *selectionArray;
    int fps;
    UITableView *tableView;
}

@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView;
@property(nonatomic) int fps; // @synthesize fps;
@property(retain, nonatomic) NSMutableArray *selectionArray; // @synthesize selectionArray;
@property(retain, nonatomic) UILabel *labelInfo; // @synthesize labelInfo;
@property(retain, nonatomic) NSArray *imagesArray; // @synthesize imagesArray;
- (void).cxx_destruct;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)selectAll:(id)arg1;
- (void)selectImage:(id)arg1;
- (void)selectImageCheck:(id)arg1;
- (void)refreshLabelTitle;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)goNext;
- (void)goBack;
- (id)initWithImages:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

