//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "RCSwitchDelegate.h"

@class NSArray, NSString, RCSwitchClone, UIScrollView;

@interface SettingsMenuViewController : UIViewController <RCSwitchDelegate>
{
    RCSwitchClone *pushNotificationsSwitch;
    NSArray *labels;
    UIScrollView *_mainScrollView;
}

@property(nonatomic) __weak UIScrollView *mainScrollView; // @synthesize mainScrollView=_mainScrollView;
@property(retain, nonatomic) NSArray *labels; // @synthesize labels;
@property(nonatomic) __weak RCSwitchClone *pushNotificationsSwitch; // @synthesize pushNotificationsSwitch;
- (void).cxx_destruct;
- (void)guidelinesPressed:(id)arg1;
- (void)privacyPolicyPressed:(id)arg1;
- (void)termsOfServicePressed:(id)arg1;
- (void)supportPressed:(id)arg1;
- (void)inviteFriendsPressed:(id)arg1;
- (void)findUsersPressed:(id)arg1;
- (void)aboutUsPressed:(id)arg1;
- (void)editProfilePressed:(id)arg1;
- (void)viewProfilePressed:(id)arg1;
- (void)logoutPressed:(id)arg1;
- (void)valueChanged:(id)arg1 toValue:(BOOL)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

