//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "STTwitterProtocol.h"

@class NSString;

@interface STTwitterAppOnly : NSObject <STTwitterProtocol>
{
    NSString *_consumerName;
    NSString *_consumerKey;
    NSString *_consumerSecret;
    NSString *_bearerToken;
}

+ (id)base64EncodedBearerTokenCredentialsWithConsumerKey:(id)arg1 consumerSecret:(id)arg2;
+ (id)twitterAppOnlyWithConsumerName:(id)arg1 consumerKey:(id)arg2 consumerSecret:(id)arg3;
@property(retain, nonatomic) NSString *bearerToken; // @synthesize bearerToken=_bearerToken;
@property(retain, nonatomic) NSString *consumerSecret; // @synthesize consumerSecret=_consumerSecret;
@property(retain, nonatomic) NSString *consumerKey; // @synthesize consumerKey=_consumerKey;
@property(retain, nonatomic) NSString *consumerName; // @synthesize consumerName=_consumerName;
- (void).cxx_destruct;
- (id)loginTypeDescription;
- (id)postResource:(id)arg1 baseURLString:(id)arg2 parameters:(id)arg3 uploadProgressBlock:(CDUnknownBlockType)arg4 downloadProgressBlock:(CDUnknownBlockType)arg5 successBlock:(CDUnknownBlockType)arg6 errorBlock:(CDUnknownBlockType)arg7;
- (id)postResource:(id)arg1 baseURLString:(id)arg2 parameters:(id)arg3 useBasicAuth:(BOOL)arg4 uploadProgressBlock:(CDUnknownBlockType)arg5 downloadProgressBlock:(CDUnknownBlockType)arg6 successBlock:(CDUnknownBlockType)arg7 errorBlock:(CDUnknownBlockType)arg8;
- (id)fetchResource:(id)arg1 HTTPMethod:(id)arg2 baseURLString:(id)arg3 parameters:(id)arg4 uploadProgressBlock:(CDUnknownBlockType)arg5 downloadProgressBlock:(CDUnknownBlockType)arg6 successBlock:(CDUnknownBlockType)arg7 errorBlock:(CDUnknownBlockType)arg8;
- (id)getResource:(id)arg1 baseURLString:(id)arg2 parameters:(id)arg3 progressBlock:(CDUnknownBlockType)arg4 successBlock:(CDUnknownBlockType)arg5 errorBlock:(CDUnknownBlockType)arg6;
- (void)verifyCredentialsWithSuccessBlock:(CDUnknownBlockType)arg1 errorBlock:(CDUnknownBlockType)arg2;
- (void)invalidateBearerTokenWithSuccessBlock:(CDUnknownBlockType)arg1 errorBlock:(CDUnknownBlockType)arg2;
- (id)oauthAccessTokenSecret;
- (id)oauthAccessToken;
- (BOOL)canVerifyCredentials;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

