//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "STTwitterProtocol.h"

@class ACAccount, ACAccountStore, NSString;

@interface STTwitterOS : NSObject <STTwitterProtocol>
{
    ACAccountStore *_accountStore;
    ACAccount *_account;
}

+ (id)parametersDictionaryFromAmpersandSeparatedParameterString:(id)arg1;
+ (id)parametersDictionaryFromCommaSeparatedParametersString:(id)arg1;
+ (id)twitterAPIOSWithFirstAccount;
+ (id)twitterAPIOSWithAccount:(id)arg1;
@property(retain, nonatomic) ACAccount *account; // @synthesize account=_account;
@property(retain, nonatomic) ACAccountStore *accountStore; // @synthesize accountStore=_accountStore;
- (void).cxx_destruct;
- (void)postReverseAuthAccessTokenWithAuthenticationHeader:(id)arg1 successBlock:(CDUnknownBlockType)arg2 errorBlock:(CDUnknownBlockType)arg3;
- (id)fetchResource:(id)arg1 HTTPMethod:(id)arg2 baseURLString:(id)arg3 parameters:(id)arg4 uploadProgressBlock:(CDUnknownBlockType)arg5 downloadProgressBlock:(CDUnknownBlockType)arg6 successBlock:(CDUnknownBlockType)arg7 errorBlock:(CDUnknownBlockType)arg8;
- (id)fetchAPIResource:(id)arg1 baseURLString:(id)arg2 httpMethod:(int)arg3 parameters:(id)arg4 uploadProgressBlock:(CDUnknownBlockType)arg5 completionBlock:(CDUnknownBlockType)arg6 errorBlock:(CDUnknownBlockType)arg7;
- (void)verifyCredentialsWithSuccessBlock:(CDUnknownBlockType)arg1 errorBlock:(CDUnknownBlockType)arg2;
- (BOOL)hasAccessToTwitter;
- (BOOL)canVerifyCredentials;
- (id)loginTypeDescription;
- (id)consumerName;
- (id)username;
- (id)initWithAccount:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

